### PR TITLE
MERGE NOT NECESSARY: add test program that fails

### PR DESCRIPTION
**Pull request by Johannes-Sahlmann**
This PR adds the OTE-10 program to test_data/misc which uses fiducial point overrides.

test_apt_interface fails with 
`AssertionError: Inconsistent table size from XML file (28) and pointing file (30). Something was not processed correctly in apt_inputs.`

which is related to something being missed in observation 6 .

### CODE REVIEW

**Comment by laurenmarietta** [comment]
Hi @Johannes-Sahlmann - I'm a little confused about this PR. Is it a WIP that you are working on fixing the problems with OTE-10? Would you like me to fix those problems? Or just a way to document the problem?

**Comment by Johannes-Sahlmann** [comment]
Hi @laurenmarietta , my apologies for being ambiguous. This PR is meant as a way to communicate that I found a small problem with the current branch and make the concerned test data available at the same time. I am not sure where the problem is. Could you please have a look and let me know if you think it is related to the fiducial point override part? If yes, do you think you can fix it?
If not, I can try to address the problem.

**Comment by laurenmarietta** [comment]
Ah, understood. Thanks for clarifying. I'll take a look now and let you know what I find out!

**Comment by laurenmarietta** [comment]
I found something odd, which is when I load program 1144 in APT, I get a set of observations that is different from these files you have uploaded. Here's the pointing file that I get out, so you can see what I mean:

[OTE10-1144_pointing.txt](https://github.com/laurenmarietta/mirage/files/2687755/OTE10-1144_pointing.txt)

This doesn't negate the fact that there is still a bug in processing the files you provided, which I'm still looking into, but I'm wondering which version of the program is the correct one, and why they would be different?

**Comment by laurenmarietta** [comment]
(Also, I've nailed down that the error is due to the fact that subpixel dithers are no longer being taken into consideration in the `generate_observationlist.expand_for_dithers` function)

**Comment by laurenmarietta** [comment]
Okay, I believe I have fixed this error with the latest commits to spacetelescope/mirage#214. I'm going to close this issue now, and further conversation can happen over on the main issue, if necessary?

**Comment by Johannes-Sahlmann** [comment]
There are currently two OTE-10 programs in the test_data directory. One is in the NIRCam folder (the one you were looking at), the other one is in the misc/ folder and is the revised version which I am still working on. On top of that, they have very similar names. In any case, you should be looking at `misc/01144/OTE-10_1144.pointing`

**Pull request closed without merging**
